---
apiVersion: v1
kind: Service
metadata:
  name: maven
spec:
  selector:
    app: maven
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: maven
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: maven
        tier: backend
        track: stable
    spec:
      containers:
        - name: maven
          image: "samraazeem/maven:maven"
          ports:
            - name: http
              containerPort: 8080
